2019/09/09 23:20:14 [error] [questionnaire-api] [traceid:24a4fcd89557a6ecf813ca08885ac026] [spanid:5d766dae93f2e] [parentid:0] trace[IndexLogic.php:128,app\models\logic\IndexLogic->saveAnswer] 写入问卷失败,uid=3,params=[{"id":"1","answer":"3"},{"id":"2","answer":"3"},{"id":"3","answer":"5"}]
2019/09/09 23:20:14 [error] [questionnaire-api] [traceid:24a4fcd89557a6ecf813ca08885ac026] [spanid:5d766dae93f2e] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] Exception: 提交失败,请重新提交 in /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/IndexLogic.php:129
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(95): app\models\logic\IndexLogic->saveAnswer(3, Array)
#1 [internal function]: app\controllers\IndexController->actionSaveAnswer()
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-answer', Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-answer', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-answ...', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#9 {main}
2019/09/09 23:21:21 [error] [questionnaire-api] [traceid:e8d132010035ca118c5fad59a4c0a3ff] [spanid:5d766df1bb287] [parentid:0] trace[IndexLogic.php:128,app\models\logic\IndexLogic->saveAnswer] 写入问卷失败,uid=3,params=[{"id":"1","answer":"3"},{"id":"2","answer":"3"},{"id":"3","answer":"5"}],yii\base\ErrorException: Array to string conversion in /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ColumnSchema.php:157
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ColumnSchema.php(157): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/Users/oujun/Ph...', 157, Array)
#1 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(49): yii\db\ColumnSchema->typecast(Array)
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/QueryBuilder.php(375): yii\db\mysql\ColumnSchema->dbTypecast(Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(249): yii\db\QueryBuilder->prepareInsertValues('answer_source', Array, Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/QueryBuilder.php(345): yii\db\mysql\QueryBuilder->prepareInsertValues('answer_source', Array, Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(470): yii\db\QueryBuilder->insert('answer_source', Array, Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->insert('answer_source', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php(549): yii\db\Schema->insert('answer_source', Array)
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#9 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#10 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/data/AnswerSourceData.php(30): yii\db\BaseActiveRecord->save()
#11 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/IndexLogic.php(121): app\models\data\AnswerSourceData->save(Array)
#12 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(95): app\models\logic\IndexLogic->saveAnswer(3, Array)
#13 [internal function]: app\controllers\IndexController->actionSaveAnswer()
#14 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-answer', Array)
#17 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-answer', Array)
#18 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-answ...', Array)
#19 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#21 {main}
2019/09/09 23:21:21 [error] [questionnaire-api] [traceid:e8d132010035ca118c5fad59a4c0a3ff] [spanid:5d766df1bb287] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] Exception: 提交失败,请重新提交 in /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/IndexLogic.php:129
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(95): app\models\logic\IndexLogic->saveAnswer(3, Array)
#1 [internal function]: app\controllers\IndexController->actionSaveAnswer()
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-answer', Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-answer', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-answ...', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#9 {main}
2019/09/09 23:21:57 [error] [questionnaire-api] [traceid:993fc1a04cae8a9c19785b6298f9e145] [spanid:5d766e1514f84] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] TypeError: Argument 1 passed to app\helpers\ResponseHelper::outputJson() must be of the type array, boolean given, called in /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php on line 97 and defined in /Users/oujun/PhpProject/wzl/questionnaire-api/app/helpers/ResponseHelper.php:24
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(97): app\helpers\ResponseHelper::outputJson(true)
#1 [internal function]: app\controllers\IndexController->actionSaveAnswer()
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-answer', Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-answer', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-answ...', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#9 {main}
2019/09/09 23:24:29 [error] [questionnaire-api] [traceid:ed74dfc86565c94aae8f5fe0457cdf1a] [spanid:5d766ead68230] [parentid:0] trace[IndexLogic.php:95,app\models\logic\IndexLogic->saveAnswer] 用户不存在，uid=3
2019/09/09 23:24:29 [error] [questionnaire-api] [traceid:ed74dfc86565c94aae8f5fe0457cdf1a] [spanid:5d766ead68230] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] Exception: 用户不存在 in /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/IndexLogic.php:96
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(95): app\models\logic\IndexLogic->saveAnswer(3, Array)
#1 [internal function]: app\controllers\IndexController->actionSaveAnswer()
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-answer', Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-answer', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-answ...', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#9 {main}
2019/09/09 23:26:07 [error] [questionnaire-api] [traceid:116daed2de5d33575b61ea640723158a] [spanid:5d766f0fa6eef] [parentid:0] trace[IndexLogic.php:71,app\models\logic\IndexLogic->saveUserInfo] 该身份证号用户已提交问卷,params={"sex":"A","username":"oujun","idcard":"123456","mobile":"18782931195","position":"\u5e94\u8058\u5c97\u4f4d","sourcePlace":"\u751f\u6e90\u5730","age":18,"nation":"\u540d\u65cf","politicalStatus":1,"maritalStatus":"B","education":"D","workTime":1,"workPlace":"\u5de5\u8d44\u5730\u5740","childrenOrNot":"B","childrenSex":"B","childrenAge":2,"parentWorkStatus":"A","socialScale":10}
2019/09/09 23:26:07 [error] [questionnaire-api] [traceid:116daed2de5d33575b61ea640723158a] [spanid:5d766f0fa6eef] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] Exception: 您已提交问卷 in /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/IndexLogic.php:72
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/IndexController.php(72): app\models\logic\IndexLogic->saveUserInfo(Array)
#1 [internal function]: app\controllers\IndexController->actionSaveUser()
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('save-user', Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('save-user', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('index/save-user', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#9 {main}
2019/09/09 23:29:42 [error] [questionnaire-api] [traceid:a531b307717dc18be05a6af4e25c5bd6] [spanid:5d766fe622dd5] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause' in /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ActiveQuery.php(292): yii\db\Query->one(NULL)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/data/AnswerData.php(44): yii\db\ActiveQuery->one()
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/AdminLogic.php(257): app\models\data\AnswerData->getDetail(3)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/AdminController.php(73): app\models\logic\AdminLogic->answerDetail(3)
#8 [internal function]: app\controllers\AdminController->actionAnswerDetail()
#9 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('answer-detail', Array)
#12 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('answer-detail', Array)
#13 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/answer-de...', Array)
#14 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#15 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#16 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'
The SQL being executed was: SELECT * FROM `answer` WHERE (`uid`=3) AND (`status`=1) ORDER BY `ctime` DESC in /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM `...')
#1 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/db/ActiveQuery.php(292): yii\db\Query->one(NULL)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/data/AnswerData.php(44): yii\db\ActiveQuery->one()
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/AdminLogic.php(257): app\models\data\AnswerData->getDetail(3)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/AdminController.php(73): app\models\logic\AdminLogic->answerDetail(3)
#8 [internal function]: app\controllers\AdminController->actionAnswerDetail()
#9 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('answer-detail', Array)
#12 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('answer-detail', Array)
#13 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/answer-de...', Array)
#14 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#15 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#16 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'status' in 'where clause'
)

2019/09/09 23:30:19 [error] [questionnaire-api] [traceid:920c38553fab312ca95fab324d081fbc] [spanid:5d76700ba1c21] [parentid:0] trace[Controller.php:135,app\components\Controller->runAction] yii\base\ErrorException: Undefined index: totalPoints in /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/AdminLogic.php:278
Stack trace:
#0 /Users/oujun/PhpProject/wzl/questionnaire-api/app/models/logic/AdminLogic.php(278): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/oujun/Ph...', 278, Array)
#1 /Users/oujun/PhpProject/wzl/questionnaire-api/app/controllers/AdminController.php(73): app\models\logic\AdminLogic->answerDetail(3)
#2 [internal function]: app\controllers\AdminController->actionAnswerDetail()
#3 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /Users/oujun/PhpProject/wzl/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('answer-detail', Array)
#6 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('answer-detail', Array)
#7 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/answer-de...', Array)
#8 /Users/oujun/PhpProject/wzl/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /Users/oujun/PhpProject/wzl/questionnaire-api/public/index.php(17): yii\base\Application->run()
#10 {main}
2019/09/11 09:02:17 [error] [questionnaire-api] [traceid:8c465374de47a167def3853ca8e136d0] [spanid:5d7847999871b] [parentid:0] trace[CheckUserToken.php:47,app\components\filters\CheckUserToken->beforeAction] yii\base\InvalidArgumentException: Key "uid" is not a column name and can not be used as a filter in /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php:238
Stack trace:
#0 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#1 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#2 /Users/oujun/PhpProject/test/questionnaire-api/app/models/data/AdminUserData.php(36): yii\db\BaseActiveRecord::findOne(Array)
#3 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(137): app\models\data\AdminUserData->getDetailByUid(1)
#4 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(117): app\models\logic\AdminLogic->getToken(1)
#5 /Users/oujun/PhpProject/test/questionnaire-api/app/components/filters/CheckUserToken.php(37): app\models\logic\AdminLogic->checkToken(1, '23c93e76d9485e1...')
#6 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/ActionFilter.php(77): app\components\filters\CheckUserToken->beforeAction(Object(yii\base\InlineAction))
#7 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#8 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\ActionEvent))
#9 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(276): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#10 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#11 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#12 /Users/oujun/PhpProject/test/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('index', Array)
#13 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('index', Array)
#14 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#15 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /Users/oujun/PhpProject/test/questionnaire-api/public/index.php(17): yii\base\Application->run()
#17 {main}
2019/09/11 09:02:29 [error] [questionnaire-api] [traceid:8cebc5054f1d2471bccca337761e8473] [spanid:5d7847a5168b1] [parentid:0] trace[CheckUserToken.php:47,app\components\filters\CheckUserToken->beforeAction] yii\base\InvalidArgumentException: Key "uid" is not a column name and can not be used as a filter in /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php:238
Stack trace:
#0 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#1 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#2 /Users/oujun/PhpProject/test/questionnaire-api/app/models/data/AdminUserData.php(36): yii\db\BaseActiveRecord::findOne(Array)
#3 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(137): app\models\data\AdminUserData->getDetailByUid(1)
#4 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(117): app\models\logic\AdminLogic->getToken(1)
#5 /Users/oujun/PhpProject/test/questionnaire-api/app/components/filters/CheckUserToken.php(37): app\models\logic\AdminLogic->checkToken(1, '23c93e76d9485e1...')
#6 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/ActionFilter.php(77): app\components\filters\CheckUserToken->beforeAction(Object(yii\base\InlineAction))
#7 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#8 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\ActionEvent))
#9 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(276): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#10 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#11 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#12 /Users/oujun/PhpProject/test/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('index', Array)
#13 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('index', Array)
#14 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#15 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /Users/oujun/PhpProject/test/questionnaire-api/public/index.php(17): yii\base\Application->run()
#17 {main}
2019/09/11 09:02:30 [error] [questionnaire-api] [traceid:61a514cc44e65370b316b5fbe6f99bbb] [spanid:5d7847a6915e1] [parentid:0] trace[CheckUserToken.php:47,app\components\filters\CheckUserToken->beforeAction] yii\base\InvalidArgumentException: Key "uid" is not a column name and can not be used as a filter in /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php:238
Stack trace:
#0 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#1 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#2 /Users/oujun/PhpProject/test/questionnaire-api/app/models/data/AdminUserData.php(36): yii\db\BaseActiveRecord::findOne(Array)
#3 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(137): app\models\data\AdminUserData->getDetailByUid(1)
#4 /Users/oujun/PhpProject/test/questionnaire-api/app/models/logic/AdminLogic.php(117): app\models\logic\AdminLogic->getToken(1)
#5 /Users/oujun/PhpProject/test/questionnaire-api/app/components/filters/CheckUserToken.php(37): app\models\logic\AdminLogic->checkToken(1, '23c93e76d9485e1...')
#6 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/ActionFilter.php(77): app\components\filters\CheckUserToken->beforeAction(Object(yii\base\InlineAction))
#7 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#8 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\ActionEvent))
#9 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(276): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#10 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#11 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#12 /Users/oujun/PhpProject/test/questionnaire-api/app/components/Controller.php(133): yii\base\Controller->runAction('index', Array)
#13 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Module.php(528): app\components\Controller->runAction('index', Array)
#14 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#15 /Users/oujun/PhpProject/test/questionnaire-api/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /Users/oujun/PhpProject/test/questionnaire-api/public/index.php(17): yii\base\Application->run()
#17 {main}
